### ISSUE TITLE
Mangahere Not working

### ISSUE THREAD

**Issue by azaziel666** [anka-213/webcomic_reader#100]
Webcomic reader no longer works on Mangahere or Mangafox. Does anyone know why?
I know they added a special "featured page" between each chapter, did that mess the script up?

**Comment by ibnuda** [comment]
Should be fixed by [this](https://github.com/anka-213/webcomic_reader/commit/a7a4dcfbb0341577bbc4ae603ea33abfc96803fc) commit.
![screenshot-2018-5-19 hiraheishi wa kako o yumemiru 21 - read hiraheishi wa kako o yumemiru chapter 21 online](https://user-images.githubusercontent.com/8169908/40255062-08d100b2-5b10-11e8-86e1-87c4990bf67e.png)

**Comment by anka-213** [comment]
@ibnuda Thanks. I'm closing this then.
