### ISSUE TITLE
mangaseeonline.us no longer available

### ISSUE THREAD

**Issue by kobuki** [anka-213/webcomic_reader#142]
mangaseeonline.us was working perfectly about 2-3 weeks ago but now it has entirely disappeared from the code base. Could it be put back? It's one of the sites not using additional compression on the images and thus I tend to use it to read a few certain manga.

**Comment by kobuki** [comment]
Well, sorry, one change had to be made I forgot about:

```
// @include     http*://mangasee.co/manga/*
// @include     http*://mangaseeonline.us/* 
```
Because it now uses https instead of http. Other than that it has been a good working site. I can make a pull request if needed.

**Comment by SoraHjort** [comment]
Sorry, that was more than likely my fault. A lot of manga sites got culled in a massive dead site cleanup effort a while back. While I can't remember the exact reason why it got thrown in, it might have to do with the first domain being a dead site. (Last major pull)

Did a quick check with with a reversion on that, and yes it does work. 

I am working on some additional fixes and additions that I'll eventually put in a pull request for. I've placed the fix into it, so the next time I do put in a pull, it'll be fixed. But since that might be a while still, you can access that fix temporarily over at:

https://github.com/SoraHjort/webcomic_reader/blob/Fixes-and-Additions/webcomic_reader.user.js

That should get you back up and running for the site. (One of the major changes was converting all includes to http* to prevent switching to or from https from breaking the script, which might have prevented this mixup)

**Comment by kobuki** [comment]
Thanks for the explanation. Yes, I've found the ominous PR that killed a lot of sites. That's actually a good thing but yeah, sh*t happens sometimes, no problem. I've edited my local copy for the time being, I'll mark this issue solved when the new PR you mentioned is merged.

**Comment by anka-213** [comment]
This should be fixed now
