### ISSUE TITLE
Site support request [webtoons.com]

### ISSUE THREAD

**Issue by YogSottot** [anka-213/webcomic_reader#28]
http://www.webtoons.com

**Comment by anka-213** [comment]
It's not trivial to add, since most comics there are long vertical strips consisting of many images per page, and the script is made for one image per page. What feature(s) of the script would be most helpful for you on this site?

**Comment by YogSottot** [comment]
> navigate using the back/next buttons, left/right arrow keys, or clicking the image itself (on the right half to go forward, on the left to go backwards). Preloads up to 5 (or more) pages ahead (in either direction, in case you want to start from the end...)

**Comment by anka-213** [comment]
I've added the site now. The only problem is that it only preloads the first image on each page. If (you think that) the speed is a big problem, I might look into how to preload more.

For now, you might as well limit the prefetching to one page for the site, since loading the first image on several pages doesn't help much.

Please reopen the issue if you still need full preloading or there is something else of importance missing.
