### ISSUE TITLE
Kissmanga bookmarks not keeping their page position.

### ISSUE THREAD

**Issue by darklinkpower** [anka-213/webcomic_reader#7]
Every site I've used works fine, but kissmanga.com bookmarks are not working correctly, because when I save a bookmar ona certain page, upon loading, the chapter will be loaded but on the first page, not the one I saved the  bookmark in.

**Comment by anka-213** [comment]
It seems like that feature never worked on kissmanga.com, but now it should be fixed. I also fixed the chapter switching and added support for going backwards on the site.

You need to set reading type to "All Pages", otherwise the javascript on the site will interfer with this script.

As a side note, this is now the first site (I know of) on which going back from the start of a chapter actually goes to the end of the previous chapter, instead of the start of it. ;)
